spring.datasource.url=jdbc:postgresql://localhost:5432/nutriplan_db
spring.datasource.username=nutriuser
spring.datasource.password=nutripassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://emmoacbqfifpcujiuqkr.supabase.co/auth/v1

app.security.cors.allowed-origins=http://localhost:3000,http://localhost:4200

logging.level.org.springframework.security=INFO

# Temporal para desarrollo mientras Spring AI no esté integrado de verdad
spring.ai.azure.openai.api-key=dummy-key
spring.ai.azure.openai.endpoint=https://dummy-endpoint.openai.azure.com/
spring.ai.azure.openai.chat.options.deployment-name=gpt-35-turbo